import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, copyFileSync, writeFileSync, chmodSync } from "node:fs";
import { isIPv4 } from "node:net";
import { networkInterfaces } from "node:os";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const address = process.argv[2];
const addresses = Object.values(networkInterfaces())
  .flat()
  .filter(Boolean)
  .filter((entry) => entry.family === "IPv4" && !entry.internal)
  .map((entry) => entry.address);

try {
  if (process.argv.length !== 3 || !isIPv4(address ?? "") || !addresses.includes(address)) {
    throw new Error(
      "Run npm run lan:setup -- <local IPv4 address>. Available addresses: " + addresses.join(", "),
    );
  }
  let caRoot;
  try {
    caRoot = execFileSync("mkcert", ["-CAROOT"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    }).trim();
  } catch {
    throw new Error(
      "Install mkcert and configure its local CA before running lan:setup. See README.md.",
    );
  }
  if (
    !existsSync(resolve(caRoot, "rootCA.pem")) ||
    !existsSync(resolve(caRoot, "rootCA-key.pem"))
  ) {
    throw new Error("Configure the local CA with mkcert -install, then run lan:setup again.");
  }
  const directory = resolve(root, ".cache/lan");
  mkdirSync(directory, { recursive: true, mode: 0o700 });
  execFileSync(
    "mkcert",
    [
      "-cert-file",
      resolve(directory, "server.pem"),
      "-key-file",
      resolve(directory, "server-key.pem"),
      address,
      "localhost",
      "127.0.0.1",
    ],
    { stdio: ["ignore", "pipe", "pipe"] },
  );
  chmodSync(resolve(directory, "server-key.pem"), 0o600);
  // Only the public root is copied for installation on the test phone.
  copyFileSync(resolve(caRoot, "rootCA.pem"), resolve(directory, "rootCA.cer"));
  writeFileSync(
    resolve(root, ".env.lan.local"),
    [
      "# Generated by lan:setup. Loaded only by dev:lan and invite:lan.",
      `APP_ORIGIN=https://${address}:3000`,
      `LAN_DEV_HOST=${address}`,
      "NODE_EXTRA_CA_CERTS=.cache/lan/rootCA.cer",
      "",
    ].join("\n"),
    { mode: 0o600 },
  );
  console.log(`Local HTTPS origin: https://${address}:3000`);
  console.log("Start with npm run dev:lan. Create matching invitations with npm run invite:lan.");
  console.log(
    "Install and trust .cache/lan/rootCA.cer on the test phone. Never share private key files.",
  );
  console.log(
    "No trust settings or .env.local values were changed. Admission keeps its existing setting.",
  );
} catch (error) {
  console.error(
    error instanceof Error && !("status" in error)
      ? error.message
      : "Certificate setup failed. Check the local mkcert installation.",
  );
  process.exitCode = 1;
}
